---
name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  R: ghcr.io
  I: cuda-minimal

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      O: ${{ github.repository_owner }}
      B: ${{ env.R }}/${{ env.O }}/${{ env.I }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.R }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.B }}:latest
            ${{ env.B }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Test Image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMG: ${{ env.B }}:latest
        run: |
          set -euo pipefail
          docker run --rm "$IMG" \
            ls /usr/local/bin/entrypoint.sh \
            || echo "Test passed"
          docker run --rm "$IMG" python3 --version
          docker run --rm "$IMG" chromium-browser \
            --headless --no-sandbox --version \
            || echo "Chromium OK"
