name: build-and-publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr:
    name: Build and push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: docker-ubuntu-nvidia
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}
          cache-to: type=gha,mode=max,scope=${{ env.IMAGE_NAME }}

  mirror-dockerhub:
    name: Mirror GHCR → Docker Hub
    needs: ghcr
    if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | skopeo login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | skopeo login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Copy latest (retry x3)
        run: |
          for i in 1 2 3; do
            skopeo copy --all \
              docker://ghcr.io/${{ github.repository_owner }}/docker-ubuntu-nvidia:latest \
              docker://docker.io/${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-nvidia:latest && break || sleep 20
          done

      - name: Copy by commit SHA (retry x3)
        run: |
          for i in 1 2 3; do
            skopeo copy --all \
              docker://ghcr.io/${{ github.repository_owner }}/docker-ubuntu-nvidia:${{ github.sha }} \
              docker://docker.io/${{ secrets.DOCKERHUB_USERNAME }}/docker-ubuntu-nvidia:${{ github.sha }} && break || sleep 20
          done
