name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      R: ghcr.io
      I: cuda-minimal
      O: ${{ github.repository_owner }}
    steps:
      - name: Set B
        run: echo "B=${R}/${O}/${I}" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      # ... (rest of your steps, now can use ${{ env.B }})
